import * as Server from "@verisure/server";
import * as Context from "effect/Context";
import * as Effect from "effect/Effect";
import * as Layer from "effect/Layer";
import * as Redacted from "effect/Redacted";
import * as HttpRouter from "effect/unstable/http/HttpRouter";
import {
  HttpApiError,
  HttpApiMiddleware,
  HttpApiSecurity,
  OpenApi,
} from "effect/unstable/httpapi";

import { ShortcutMfaRequired } from "./ShortcutErrors";

class ShortcutBearerToken extends Context.Service<
  ShortcutBearerToken,
  { readonly value: string }
>()("@verisure/api/Http/ShortcutBearerToken") {}

class ShortcutAuthenticatedToken extends Context.Service<
  ShortcutAuthenticatedToken,
  Server.AuthenticatedApiToken
>()("@verisure/api/Http/ShortcutAuthenticatedToken") {}

export class ShortcutAuthorization extends HttpApiMiddleware.Service<
  ShortcutAuthorization,
  { readonly provides: ShortcutBearerToken }
>()("@verisure/api/Http/ShortcutAuthorization", {
  error: HttpApiError.UnauthorizedNoContent,
  security: {
    bearer: HttpApiSecurity.bearer.pipe(
      HttpApiSecurity.annotate(
        OpenApi.Description,
        "Shortcut API bearer token generated by the dashboard"
      )
    ),
  },
}) {}

export class ShortcutApiTokenPrincipal extends HttpApiMiddleware.Service<
  ShortcutApiTokenPrincipal,
  {
    readonly provides:
      | Server.CurrentUser
      | Server.CurrentCredential
      | ShortcutAuthenticatedToken;
    readonly requires: ShortcutBearerToken;
  }
>()("@verisure/api/Http/ShortcutApiTokenPrincipal", {
  error: [HttpApiError.UnauthorizedNoContent, HttpApiError.ForbiddenNoContent],
}) {}

export class ShortcutAlarmReadAccess extends HttpApiMiddleware.Service<
  ShortcutAlarmReadAccess,
  {
    readonly provides: Server.CurrentInstallation;
    readonly requires: Server.CurrentCredential | ShortcutAuthenticatedToken;
  }
>()("@verisure/api/Http/ShortcutAlarmReadAccess", {
  error: [
    HttpApiError.BadRequestNoContent,
    HttpApiError.ForbiddenNoContent,
    HttpApiError.NotFoundNoContent,
    ShortcutMfaRequired,
    HttpApiError.ServiceUnavailableNoContent,
  ],
}) {}

export class ShortcutAlarmWriteAccess extends HttpApiMiddleware.Service<
  ShortcutAlarmWriteAccess,
  {
    readonly provides: Server.CurrentInstallation;
    readonly requires: Server.CurrentCredential | ShortcutAuthenticatedToken;
  }
>()("@verisure/api/Http/ShortcutAlarmWriteAccess", {
  error: [
    HttpApiError.BadRequestNoContent,
    HttpApiError.ForbiddenNoContent,
    HttpApiError.NotFoundNoContent,
    ShortcutMfaRequired,
    HttpApiError.ServiceUnavailableNoContent,
  ],
}) {}

const ShortcutAuthorizationLive = Layer.succeed(ShortcutAuthorization, {
  bearer: (effect, { credential }) => {
    const token = Redacted.value(credential);

    if (token.length === 0) {
      return Effect.fail(new HttpApiError.Unauthorized());
    }

    return Effect.provideService(
      effect,
      ShortcutBearerToken,
      ShortcutBearerToken.of({ value: token })
    );
  },
});

const ShortcutApiTokenPrincipalLive = Layer.effect(
  ShortcutApiTokenPrincipal,
  Effect.gen(function* () {
    const apiTokens = yield* Server.ApiTokenService;

    return ShortcutApiTokenPrincipal.of((effect) =>
      Effect.gen(function* () {
        const bearerToken = yield* ShortcutBearerToken;
        const authenticated = yield* apiTokens
          .authenticate({ plaintextToken: bearerToken.value })
          .pipe(
            Effect.catchTags({
              ApiTokenForbidden: () =>
                Effect.fail(new HttpApiError.Forbidden()),
              ApiTokenUnauthorized: () =>
                Effect.fail(new HttpApiError.Unauthorized()),
              ServiceUnavailable: () =>
                Effect.die(new HttpApiError.ServiceUnavailable()),
            })
          );

        return yield* effect.pipe(
          Effect.provideService(Server.CurrentUser, authenticated.user),
          Effect.provideService(
            Server.CurrentCredential,
            authenticated.credential
          ),
          Effect.provideService(
            ShortcutAuthenticatedToken,
            ShortcutAuthenticatedToken.of(authenticated)
          )
        );
      })
    );
  })
);

const ShortcutAlarmReadAccessLive = Layer.effect(
  ShortcutAlarmReadAccess,
  Effect.gen(function* () {
    const crypto = yield* Server.CredentialCrypto;
    const requests = yield* Server.VerisureRequests;
    return ShortcutAlarmReadAccess.of((effect) =>
      Effect.gen(function* () {
        const scope = Server.ShortcutAlarmReadScope;
        const giid = yield* routeGiid;
        const authenticated = yield* ShortcutAuthenticatedToken;

        if (!authenticated.token.scopes.includes(scope)) {
          return yield* new HttpApiError.Forbidden();
        }
        if (
          authenticated.token.allowedGiids !== undefined &&
          !authenticated.token.allowedGiids.includes(giid)
        ) {
          return yield* new HttpApiError.Forbidden();
        }

        const decrypted = yield* crypto
          .decryptCredential(authenticated.credential)
          .pipe(Effect.catchTag("CredentialCryptoError", Effect.die));

        const installations = yield* requests
          .fetchAllInstallations({ email: Redacted.value(decrypted.email) })
          .pipe(
            Effect.provideService(
              Server.CurrentCredential,
              authenticated.credential
            ),
            Effect.mapError(mapVerisureRequestsError)
          );

        if (!installations.some((installation) => installation.giid === giid)) {
          return yield* new HttpApiError.NotFound();
        }

        return yield* Effect.provideService(
          effect,
          Server.CurrentInstallation,
          { giid }
        );
      })
    );
  })
);

const ShortcutAlarmWriteAccessLive = Layer.effect(
  ShortcutAlarmWriteAccess,
  Effect.gen(function* () {
    const crypto = yield* Server.CredentialCrypto;
    const requests = yield* Server.VerisureRequests;
    return ShortcutAlarmWriteAccess.of((effect) =>
      Effect.gen(function* () {
        const scope = Server.ShortcutAlarmWriteScope;
        const giid = yield* routeGiid;
        const authenticated = yield* ShortcutAuthenticatedToken;

        if (!authenticated.token.scopes.includes(scope)) {
          return yield* new HttpApiError.Forbidden();
        }
        if (
          authenticated.token.allowedGiids !== undefined &&
          !authenticated.token.allowedGiids.includes(giid)
        ) {
          return yield* new HttpApiError.Forbidden();
        }

        const decrypted = yield* crypto
          .decryptCredential(authenticated.credential)
          .pipe(Effect.catchTag("CredentialCryptoError", Effect.die));

        const installations = yield* requests
          .fetchAllInstallations({ email: Redacted.value(decrypted.email) })
          .pipe(
            Effect.provideService(
              Server.CurrentCredential,
              authenticated.credential
            ),
            Effect.mapError(mapVerisureRequestsError)
          );

        if (!installations.some((installation) => installation.giid === giid)) {
          return yield* new HttpApiError.NotFound();
        }

        return yield* Effect.provideService(
          effect,
          Server.CurrentInstallation,
          { giid }
        );
      })
    );
  })
);

export const ShortcutMiddlewareLive = Layer.mergeAll(
  ShortcutAuthorizationLive,
  ShortcutApiTokenPrincipalLive,
  ShortcutAlarmReadAccessLive,
  ShortcutAlarmWriteAccessLive
);

const routeGiid = HttpRouter.params.pipe(
  Effect.flatMap((params) => {
    const { giid } = params;
    return giid === undefined || giid.length === 0
      ? Effect.fail(new HttpApiError.BadRequest())
      : Effect.succeed(giid);
  })
);

const mapVerisureRequestsError = (error: Server.VerisureRequestsError) => {
  if (error.reason instanceof Server.VerisureRequestsMfaRequired) {
    return new ShortcutMfaRequired({ message: error.reason.message });
  }

  return new HttpApiError.ServiceUnavailable();
};
