import * as Domain from "@verisure/domain";
import * as Server from "@verisure/server";
import * as Context from "effect/Context";
import * as Effect from "effect/Effect";
import * as Layer from "effect/Layer";
import * as Redacted from "effect/Redacted";
import * as HttpServerRequest from "effect/unstable/http/HttpServerRequest";
import * as HttpApiMiddleware from "effect/unstable/httpapi/HttpApiMiddleware";
import * as HttpApiSecurity from "effect/unstable/httpapi/HttpApiSecurity";
import * as OpenApi from "effect/unstable/httpapi/OpenApi";

import {
  ShortcutForbiddenError,
  ShortcutInstallationNotFoundError,
  ShortcutInvalidInputError,
  ShortcutMfaRequiredError,
  ShortcutRateLimitError,
  ShortcutServiceUnavailableError,
  ShortcutUnauthorizedError,
  ShortcutVerisureUpstreamError,
} from "./ShortcutErrors";

class ShortcutBearerToken extends Context.Service<
  ShortcutBearerToken,
  { readonly value: string }
>()("@verisure/api/Http/ShortcutBearerToken") {}

export class ShortcutAuthorization extends HttpApiMiddleware.Service<
  ShortcutAuthorization,
  { readonly provides: ShortcutBearerToken }
>()("@verisure/api/Http/ShortcutAuthorization", {
  error: ShortcutUnauthorizedError,
  security: {
    bearer: HttpApiSecurity.bearer.pipe(
      HttpApiSecurity.annotate(
        OpenApi.Description,
        "Shortcut API bearer token generated by the dashboard"
      )
    ),
  },
}) {}

export class ShortcutSchemaErrorHandler extends HttpApiMiddleware.Service<ShortcutSchemaErrorHandler>()(
  "@verisure/api/Http/ShortcutSchemaErrorHandler",
  {
    error: ShortcutInvalidInputError,
  }
) {}

const ShortcutAuthorizationLive = Layer.succeed(ShortcutAuthorization, {
  bearer: (effect, { credential }) =>
    Effect.gen(function* () {
      const request = yield* HttpServerRequest.HttpServerRequest;
      const token = yield* decodeBearerToken(
        request.headers.authorization,
        Redacted.value(credential)
      );

      return yield* Effect.provideService(
        effect,
        ShortcutBearerToken,
        ShortcutBearerToken.of({ value: token })
      );
    }),
});

const ShortcutSchemaErrorHandlerLive =
  HttpApiMiddleware.layerSchemaErrorTransform(ShortcutSchemaErrorHandler, () =>
    Effect.fail(
      new ShortcutInvalidInputError({ message: "Invalid request payload" })
    )
  );

export const ShortcutMiddlewareLive = Layer.mergeAll(
  ShortcutAuthorizationLive,
  ShortcutSchemaErrorHandlerLive
);

const decodeBearerToken = (
  authorization: string | undefined,
  credential: string
) => {
  if (authorization === undefined) {
    return Effect.fail(
      new ShortcutUnauthorizedError({ message: "Missing bearer token" })
    );
  }

  if (!/^Bearer\s+.+$/iu.test(authorization) || credential.length === 0) {
    return Effect.fail(
      new ShortcutUnauthorizedError({ message: "Invalid authorization header" })
    );
  }

  return Effect.succeed(credential);
};

type ShortcutScopeError =
  | ShortcutForbiddenError
  | ShortcutInstallationNotFoundError
  | ShortcutInvalidInputError
  | ShortcutMfaRequiredError
  | ShortcutRateLimitError
  | ShortcutServiceUnavailableError
  | ShortcutUnauthorizedError
  | ShortcutVerisureUpstreamError;

export const provideShortcutAlarmScope =
  (input: {
    readonly giid: string;
    readonly requiredScopes: readonly string[];
  }) =>
  <A, E, R>(
    effect: Effect.Effect<A, E, R>
  ): Effect.Effect<
    A,
    E | ShortcutScopeError,
    | Exclude<
        Exclude<Exclude<R, Server.CurrentUser>, Server.CurrentCredential>,
        Server.CurrentInstallation
      >
    | Server.ApiTokenService
    | Server.CredentialCrypto
    | Server.VerisureRequests
    | ShortcutBearerToken
  > =>
    Effect.gen(function* () {
      const apiTokens = yield* Server.ApiTokenService;
      const crypto = yield* Server.CredentialCrypto;
      const requests = yield* Server.VerisureRequests;
      const bearerToken = yield* ShortcutBearerToken;

      const authenticated = yield* apiTokens
        .authenticate({
          giid: input.giid,
          plaintextToken: bearerToken.value,
          requiredScopes: input.requiredScopes,
        })
        .pipe(
          Effect.mapError((error): ShortcutScopeError => {
            if (error instanceof Server.ApiTokenForbidden) {
              return new ShortcutForbiddenError({ message: error.message });
            }
            if (error instanceof Server.ApiTokenUnauthorized) {
              return new ShortcutUnauthorizedError({ message: error.message });
            }
            return new ShortcutServiceUnavailableError({
              message: error.message,
            });
          })
        );

      const decrypted = yield* crypto
        .decryptCredential(authenticated.credential)
        .pipe(
          Effect.catchTag("CredentialCryptoError", () =>
            Effect.fail(
              new ShortcutInvalidInputError({
                message: "Credential material is invalid",
              })
            )
          )
        );

      const installations = yield* requests
        .fetchAllInstallations({ email: Redacted.value(decrypted.email) })
        .pipe(
          Effect.provideService(
            Server.CurrentCredential,
            authenticated.credential
          ),
          Effect.mapError((error): ShortcutScopeError => {
            if (
              error instanceof Domain.AuthenticationError ||
              error instanceof Domain.CredentialsRejected
            ) {
              return new ShortcutUnauthorizedError({ message: error.message });
            }
            if (error instanceof Domain.MFARequired) {
              return new ShortcutMfaRequiredError({ message: error.message });
            }
            if (error instanceof Domain.RateLimitError) {
              return new ShortcutRateLimitError({ message: error.message });
            }
            return new ShortcutVerisureUpstreamError({
              message: "Unable to verify installation access",
            });
          })
        );

      if (
        !installations.some((installation) => installation.giid === input.giid)
      ) {
        return yield* new ShortcutInstallationNotFoundError({
          giid: input.giid,
          message: "Installation not found",
        });
      }

      return yield* effect.pipe(
        Effect.provideService(Server.CurrentUser, authenticated.user),
        Effect.provideService(
          Server.CurrentCredential,
          authenticated.credential
        ),
        Effect.provideService(Server.CurrentInstallation, { giid: input.giid })
      );
    });
